import test from 'node:test';import assert from 'node:assert/strict';import {seed,execute,drain,workerId,adminId,samId} from '../operations/model.mjs';
const cmd=(s,f,a,c=workerId)=>execute(s,f,{idempotency_key:crypto.randomUUID(),...a},c);
test('idempotent acknowledgment applies once',()=>{const s=seed(),t=s.tasks[0],a={assignment_id:t.assignment_id,expected_revision:2,idempotency_key:crypto.randomUUID()};const one=execute(s,'assignment_acknowledge',a,workerId);const two=execute(s,'assignment_acknowledge',a,workerId);assert.equal(one.data.revision,3);assert.equal(two.replayed,true);assert.equal(t.task_revision,3);});
test('unqualified reassignment rejected without changing owner',()=>{const s=seed(),t=s.tasks[0];assert.throws(()=>cmd(s,'assignment_reassign',{task_id:t.task_id,to_profile_id:samId,expected_revision:2},adminId),e=>e.code==='GRND-423');assert.equal(t.assignee_id,workerId);assert.equal(t.task_revision,2);});
test('worker cannot dispatch',()=>{const s=seed();assert.throws(()=>cmd(s,'task_assign',{task_id:s.tasks[1].task_id,expected_revision:1,profile_id:samId}),e=>e.code==='GRND-403');});
test('stale finalize preserves current task',()=>{const s=seed(),t=s.tasks[0];t.state='in_progress';assert.throws(()=>cmd(s,'service_finalize',{task_id:t.task_id,expected_revision:1}),e=>e.code==='GRND-409');assert.equal(t.state,'in_progress');});
test('pivot retains summer assignments',()=>{const s=seed();cmd(s,'operating_state_pivot',{expected_revision:17,to_mode:'landscaping'},adminId);assert.equal(s.tasks.length,3);assert.equal(s.tasks[2].state,'assigned');});
test('ended shift cannot finalize',()=>{const s=seed(),t=s.tasks[0];t.state='in_progress';assert.throws(()=>cmd(s,'service_finalize',{task_id:t.task_id,expected_revision:2}),e=>e.code==='GRND-425');});
test('failed command blocks subsequent same-task replay',async()=>{const s=seed(),id=s.tasks[0].task_id,q=[{fn:'task_start',caller:workerId,status:'pending',args:{task_id:id,expected_revision:2,idempotency_key:crypto.randomUUID()}},{fn:'task_block',caller:workerId,status:'pending',args:{task_id:id,expected_revision:2,reason:'x',idempotency_key:crypto.randomUUID()}}];await drain(q,s,async()=>{});assert.equal(q[0].status,'attention');assert.equal(q[1].status,'pending');assert.equal(s.tasks[0].state,'assigned');});
