import {seed,workerId,adminId,candidates,drain} from './model.mjs';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('und-operations-preview',1);r.onupgradeneeded=()=>r.result.createObjectStore('records');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
function read(key){return new Promise((res,rej)=>{const r=db.transaction('records').objectStore('records').get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function write(key,value){return new Promise((res,rej)=>{const t=db.transaction('records','readwrite');t.objectStore('records').put(value,key);t.oncomplete=res;t.onerror=()=>rej(t.error);});}
let state=await read('state')||seed(),queue=await read('queue')||[],drafts=await read('drafts')||{},tabName='day',role='worker',offline=false,location=null,watch=null,flushing=false;
const caller=()=>role==='admin'?adminId:workerId,notice=t=>{$('#notice').textContent=t;},persist=async()=>{await write('state',state);await write('queue',queue);await write('drafts',drafts);};
function pending(t){return queue.some(c=>c.status!=='done'&&(c.args.task_id===t.task_id||c.args.assignment_id===t.assignment_id));}
async function flush(){if(offline||!navigator.onLine||flushing)return;flushing=true;try{queue=await drain(queue,state,persist,notice);await persist();render();}finally{flushing=false;}}
async function command(fn,args){queue.push({id:crypto.randomUUID(),fn,args:{...args,idempotency_key:crypto.randomUUID()},caller:caller(),status:'pending',created_at:new Date().toISOString()});await persist();$('#detail').close();notice('Action saved on this device.');await flush();render();}
function tracking(){if(watch!==null){navigator.geolocation.clearWatch(watch);watch=null;}if(state.shift&&role==='worker'&&!document.hidden&&navigator.geolocation){watch=navigator.geolocation.watchPosition(p=>{location={lng:p.coords.longitude,lat:p.coords.latitude,accuracy_m:p.coords.accuracy,taken_at:new Date(p.timestamp).toISOString()};$('#gps')&&($('#gps').textContent='Device fix · ±'+Math.round(location.accuracy_m)+' m · not uploaded');},e=>notice('Location unavailable: '+e.message+'. You can still save photos and notes.'),{enableHighAccuracy:true,maximumAge:15000,timeout:15000});}}
const freshLocation=()=>location&&Date.now()-Date.parse(location.taken_at)<30000?location:null;
function render(){
 $('#mode').textContent=state.mode==='snow'?'Snow operations':'Landscaping';$('#connection').textContent=offline||!navigator.onLine?'Offline preview':'Local simulation';$('#count').textContent=queue.length?`(${queue.length})`:'';
 document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tabName));
 if(tabName==='queue')return renderQueue();
 if(tabName==='dispatch'&&role!=='admin'){$('#content').innerHTML='<h1>Dispatch</h1><p>Choose Supervisor Test to try the dispatch workspace. Actual access will be enforced by the backend.</p>';return;}
 const tasks=state.tasks.filter(t=>tabName==='dispatch'?!['done','canceled'].includes(t.state):t.assignee_id===workerId&&!['done','canceled'].includes(t.state));
 $('#content').innerHTML=`<div class="topline"><div><p class="eyebrow">${tabName==='day'?'YOUR WORK, IN ONE PLACE':'CREW COORDINATION'}</p><h1>${tabName==='day'?'My Day':'Dispatch'}</h1><p class="muted">${tabName==='day'?'See the task. Know the equipment. Keep work moving.':'Match the work with qualified people and keep coverage visible.'}</p></div>${tabName==='day'&&role==='worker'?`<button id="shift" class="primary">${state.shift?'End shift':'Start shift'}</button>`:role==='admin'?'<button id="pivot">Switch season</button>':''}</div>
 ${tabName==='day'?`<div class="callout"><strong>${state.shift?'Shift open':'Shift not started'}</strong> · <span id="gps">${freshLocation()?'Device location available; not uploaded':'No fresh device location'}</span><br>Foreground location only. This preview does not send or retain your GPS trail.</div>`:''}
 <div class="stats"><div class="stat"><strong>${tasks.length}</strong><span>Open assignments</span></div><div class="stat"><strong>${tasks.filter(t=>t.priority===1).length}</strong><span>Priority 1</span></div><div class="stat"><strong>${tasks.filter(t=>t.season!==state.mode).length}</strong><span>Season carryover</span></div></div><div class="cards">${tasks.map(t=>`<article class="card"><div class="card-head"><span class="tag">Priority ${t.priority} · ${esc(t.zone_id)}</span><span class="state ${t.state}">${esc(t.state.replace('_',' '))}${pending(t)?' · saved action':''}</span></div><p><strong>${esc(t.outcome)}</strong></p><div class="muted">${esc(t.zone_name)}${t.season!==state.mode?' · Carryover work':''}<br>${esc(t.asset_name||'No equipment assigned')}${tabName==='dispatch'?'<br>'+esc(state.people.find(p=>p.profile_id===t.assignee_id)?.full_name||'Unassigned'):''}</div><div class="card-foot"><small>${esc(t.required_capabilities.join(' · '))}</small><button data-open="${t.task_id}">${tabName==='dispatch'?'Manage assignment':'View task'} →</button></div></article>`).join('')||'<div class="card">No open tasks. Your supervisor can assign the next job.</div>'}</div>`;
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openTask(b.dataset.open));
 if($('#shift'))$('#shift').onclick=async()=>{if(state.shift){trackingStop();await command('shift_end',{shift_id:state.shift.shift_id});notice('Shift end saved. Unfinished assignments remain visible.');}else{await command('shift_start',{device_id:'local-preview'});tracking();}};
 if($('#pivot'))$('#pivot').onclick=()=>command('operating_state_pivot',{expected_revision:state.revision,to_mode:state.mode==='snow'?'landscaping':'snow',reason:'Synthetic preview toggle'});
}
function trackingStop(){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;location=null;}
function renderQueue(){$('#content').innerHTML=`<h1>Saved actions</h1><p class="muted">Pending actions replay in order. Conflicts stay here for review; photos are retained.</p><div class="cards">${queue.map(c=>`<article class="card"><h3>${esc(c.fn.replaceAll('_',' '))}</h3><p>${esc(c.error||'Waiting to synchronize with the local simulator')}</p><span class="state">${esc(c.status)}</span>${c.status==='attention'?`<button data-dismiss="${c.id}">Dismiss action, keep evidence</button>`:''}</article>`).join('')||'<div class="card">All local actions processed.</div>'}</div>`;document.querySelectorAll('[data-dismiss]').forEach(b=>b.onclick=async()=>{queue=queue.filter(c=>c.id!==b.dataset.dismiss);await persist();await flush();render();});}
async function openTask(id){const t=state.tasks.find(x=>x.task_id===id);const d=drafts[id]||{photos:[],notes:'',qty:'',material:'bulk_salt',unit:'lb'};drafts[id]=d;
 $('#detail-content').innerHTML=`<p class="eyebrow">${esc(t.zone_name)} · ${esc(t.state)}</p><h2>${esc(t.outcome)}</h2><p class="muted">${esc(t.asset_name||'No equipment assigned')}<br>Required: ${esc(t.required_capabilities.join(', '))}</p><div id="task-actions"></div>`;
 const target=$('#task-actions');
 if(pending(t)){target.innerHTML='<div class="callout">An action for this task is waiting. Review Saved actions before making another change.</div>';}
 else if(role==='admin'){
 if(t.state==='review'){target.innerHTML=`<p>Service record is ready for review. Location assessment is unavailable in this simulation.</p><button id="export">Download preview record</button><button id="approve" class="primary">Approve test completion</button>`;$('#approve').onclick=()=>command('task_approve',{task_id:id,expected_revision:t.task_revision});$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(t.service_record,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='PREVIEW-service-record.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};}
 else if(['assigned','accepted','in_progress','unassigned'].includes(t.state)){target.innerHTML='<h3>Choose a qualified person</h3>'+candidates(state,t).map(p=>`<div class="candidate"><strong>${esc(p.full_name)}</strong><small>${p.missing_capabilities.length?'Missing: '+esc(p.missing_capabilities.join(', ')):p.on_shift?'Qualified · on shift':'Off shift'}${p.current_task?'<br>Current work: '+esc(p.current_task):''}</small><button data-assign="${p.profile_id}" ${p.missing_capabilities.length||!p.on_shift||p.profile_id===t.assignee_id?'disabled':''}>${t.assignee_id?'Reassign remaining work':'Assign task'}</button></div>`).join('')+'<p class="muted">Existing equipment remains with the task. Completed evidence stays attached. Other assignments remain visible.</p>';document.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>command(t.assignee_id?'assignment_reassign':'task_assign',{task_id:id,expected_revision:t.task_revision,...(t.assignee_id?{to_profile_id:b.dataset.assign,keep_asset:true,reason:'Supervisor preview reassignment'}:{profile_id:b.dataset.assign})}));}
 else target.innerHTML='<p>Task is blocked. Supervisor unblock controls await contract clarification.</p>';
 }else if(t.assignee_id!==workerId){target.textContent='This task belongs to another worker.';}
 else if(t.state==='assigned'){target.innerHTML='<p>Accept to acknowledge that you have seen this assignment.</p><button id="accept" class="primary">Accept assignment</button>';$('#accept').onclick=()=>command('assignment_acknowledge',{assignment_id:t.assignment_id,expected_revision:t.task_revision});}
 else if(['accepted','in_progress'].includes(t.state)){
 target.innerHTML=`<div class="callout">Original test photos are saved on this device. No photo is uploaded or verified by a server.</div><label for="before">Before photo${t.evidence_required.includes('photo_before')?' (required)':''}</label><input id="before" type="file" accept="image/*" capture="environment"><div id="before-list" class="photo-list"></div>${t.state==='accepted'?'<div class="actions"><button id="start" class="primary">Start task</button></div>':`<label for="after">After photo</label><input id="after" type="file" accept="image/*" capture="environment"><div id="after-list" class="photo-list"></div><label for="material">Material</label><select id="material"><option value="bulk_salt">Bulk salt · lb</option><option value="sand">Sand · lb</option><option value="brine">Brine · gal</option></select><label for="qty">Quantity${t.evidence_required.includes('material_qty')?' (required; enter 0 if none)':''}</label><input id="qty" type="number" min="0" step="any" value="${esc(d.qty)}"><label for="notes">Completion notes</label><textarea id="notes">${esc(d.notes)}</textarea><div class="actions"><button id="finalize" class="primary">Submit test completion</button></div>`}<label for="reason">Need help? Describe the blocker</label><input id="reason" placeholder="Equipment issue, access blocked…"><button id="block">Report blocked task</button><p id="form-error" class="error" role="alert"></p>`;
 for(const kind of ['before','after']){if(!$('#'+kind))continue;$('#'+kind).onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>20*1024*1024)throw Error('Choose an image under 20 MB.');d.photos.push({client_photo_id:crypto.randomUUID(),kind,taken_at:new Date().toISOString(),blob:file});await persist();openTask(id);}catch(err){$('#form-error').textContent=err.message;}};for(const p of d.photos.filter(p=>p.kind===kind)){const url=URL.createObjectURL(p.blob);const img=document.createElement('img');img.src=url;img.alt=kind+' test photo';img.onload=()=>URL.revokeObjectURL(url);$('#'+kind+'-list').append(img);}}
 if($('#start'))$('#start').onclick=()=>{const loc=freshLocation();if(!loc){$('#form-error').textContent='A fresh device location is required. Start your shift and allow location while this page is open.';return;}command('task_start',{task_id:id,expected_revision:t.task_revision,location:loc});};
 for(const key of ['qty','notes','material'])if($('#'+key)){if(key==='material')$('#material').value=d.material;$('#'+key).oninput=async e=>{d[key]=e.target.value;d.unit=d.material==='brine'?'gal':'lb';await persist();};}
 if($('#finalize'))$('#finalize').onclick=async()=>{const loc=freshLocation();const needs=t.evidence_required;const missing=needs.filter(r=>r==='location'?!loc:r==='material_qty'?d.qty==='':!d.photos.some(p=>p.kind===r.replace('photo_','')));if(missing.length){$('#form-error').textContent='Still needed: '+missing.join(', ');return;}if(d.qty!==''&&(!Number.isFinite(Number(d.qty))||Number(d.qty)<0)){$('#form-error').textContent='Enter a quantity of zero or greater.';return;}await command('service_finalize',{task_id:id,expected_revision:t.task_revision,action:t.task_type==='shovel'?'shoveled':'inspected',started_at:t.started_at,completed_at:new Date().toISOString(),location:loc,photos:d.photos.map(({blob,...p})=>p),materials:d.qty!==''?[{material_code:d.material,qty:Number(d.qty),unit:d.unit}]:[],notes:d.notes});};
 $('#block').onclick=()=>{if(!$('#reason').value.trim()){$('#form-error').textContent='Describe the blocker first.';return;}command('task_block',{task_id:id,expected_revision:t.task_revision,reason:$('#reason').value});};
 }else target.innerHTML=`<div class="callout">${t.state==='review'?'Submitted for supervisor review. This is a test record, not verified evidence.':esc(t.blocked_reason||'No worker action available.')}</div>`;
 if(!$('#detail').open)$('#detail').showModal();
}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{tabName=b.dataset.tab;render();};
$('#persona').onchange=e=>{role=e.target.value;tabName=role==='admin'?'dispatch':'day';trackingStop();render();tracking();};
$('#offline').onchange=async e=>{offline=e.target.checked;await flush();render();};
window.addEventListener('online',()=>{flush();render();});window.addEventListener('offline',render);document.addEventListener('visibilitychange',tracking);
setInterval(()=>{if(!document.hidden){if($('#gps'))$('#gps').textContent=freshLocation()?'Device fix · ±'+Math.round(location.accuracy_m)+' m · not uploaded':'No fresh device location';if(queue.some(c=>c.status==='pending'))flush();}},30000);
render();await flush();tracking();
