import {escape,fieldError,displayTime} from './worker.mjs';
export async function showCertifications(target,{read,act,me}){
 const [capabilities,requests,qualifications,people]=await Promise.all([read('v_capabilities'),read('v_certification_requests'),read('v_qualifications'),read('v_crew_availability')]);
 target.innerHTML=`<h1>Certifications</h1><section class="card"><h2>Request a certification</h2><form id="request-cert"><label for="cert-person">Person</label><select id="cert-person">${people.map(p=>`<option value="${p.profile_id}">${escape(p.full_name)}</option>`).join('')}</select><label for="cert-capability">Capability</label><select id="cert-capability">${capabilities.map(c=>`<option value="${c.code}">${escape(c.name)}</option>`).join('')}</select><fieldset id="cert-outcomes"><legend>Training outcomes completed</legend></fieldset><label for="cert-notes">Training notes</label><textarea id="cert-notes"></textarea><button>Submit request</button><div id="cert-error" role="alert"></div></form></section><h2>Requests</h2><div class="live-list">${requests.map(r=>`<article class="card"><h3>${escape(r.full_name)} · ${escape(r.capability_name)}</h3><p>${escape(r.status)} · Requested by ${escape(r.requested_by_name)}</p><p>${escape(r.notes||'')}</p><ul>${(r.outcomes_met||[]).map(o=>`<li>${escape(o)}</li>`).join('')}</ul>${me.app_role==='admin'&&r.status==='pending'?`<label for="decision-${r.request_id}">Decision notes</label><input id="decision-${r.request_id}"><button data-decision="${r.request_id}" data-approve="true">Approve</button><button data-decision="${r.request_id}" data-approve="false">Deny</button><p data-error="${r.request_id}" role="alert"></p>`:''}</article>`).join('')||'<p>No certification requests.</p>'}</div><h2>Qualifications</h2><div class="table-scroll"><table><thead><tr><th>Person</th><th>Capability</th><th>Status</th><th>Expires</th></tr></thead><tbody>${qualifications.map(q=>`<tr><td>${escape(q.full_name)}</td><td>${escape(q.capability_name)}</td><td>${q.valid?'Valid':q.suspended?'Suspended':'Expired'}</td><td>${q.expires_at?escape(displayTime(q.expires_at)):'No expiry listed'}</td></tr>`).join('')}</tbody></table></div>`;
 const q=s=>target.querySelector(s);
 function outcomes(){const capability=capabilities.find(c=>c.code===q('#cert-capability').value);q('#cert-outcomes').innerHTML='<legend>Training outcomes completed</legend>'+(capability?.outcomes||[]).map((o,i)=>`<label><input type="checkbox" name="outcome" value="${i}" required> ${escape(o)}</label>`).join('');if(!capability?.outcomes?.length)q('#cert-outcomes').insertAdjacentHTML('beforeend','<p>No outcomes are listed for this capability.</p>');}outcomes();q('#cert-capability').onchange=outcomes;
 q('form').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{const cap=capabilities.find(c=>c.code===q('#cert-capability').value);await act('certification_request',{profile_id:q('#cert-person').value,capability_code:cap.code,outcomes_met:[...q('#cert-outcomes').querySelectorAll('input:checked')].map(input=>cap.outcomes[Number(input.value)]),notes:q('#cert-notes').value});}catch(e){fieldError(q('#cert-error'),e);button.disabled=false;}};
 target.querySelectorAll('[data-decision]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await act('certification_decide',{request_id:button.dataset.decision,approve:button.dataset.approve==='true',decision_notes:q('#decision-'+button.dataset.decision).value});}catch(e){fieldError(q(`[data-error="${button.dataset.decision}"]`),e);button.disabled=false;}});
}
