import {escape,fieldError,displayTime} from './worker.mjs';
export async function showBoard(target,{read,call,act,me}){
 const tasks=await read('v_dispatch_board',{},'priority');
 target.innerHTML=`<p class="eyebrow">Crew coordination</p><h1>Dispatch board</h1><div id="reminders"></div><section class="card"><h2>Needs your attention</h2><p>${tasks.filter(t=>t.overdue||['blocked','review'].includes(t.state)||t.state==='unassigned').length} tasks need review, assignment, or follow-up.</p><label for="board-filter">Show</label><select id="board-filter"><option value="all">All unfinished tasks</option><option value="attention">Needs your attention</option></select></section><div id="board-tasks" class="live-list"></div>`;
 const draw=()=>{const list=target.querySelector('#board-filter').value==='attention'?tasks.filter(t=>t.overdue||['blocked','review'].includes(t.state)||t.state==='unassigned'):tasks;target.querySelector('#board-tasks').innerHTML=list.map(t=>`<article class="card"><div class="card-head"><span class="tag">Priority ${t.priority} · ${escape(t.zone_name)}</span><span class="state">${escape(t.state)}</span></div><h2>${escape(t.outcome)}</h2><p>${escape(t.assignee_name||'Unassigned')} · ${escape(t.asset_name||'No equipment')}</p><p class="muted">${escape(displayTime(t.scheduled_start))}</p><button data-manage="${t.task_id}">Manage assignment</button></article>`).join('')||'<p>No tasks in this view.</p>';target.querySelectorAll('[data-manage]').forEach(b=>b.onclick=()=>manage(b.dataset.manage));};draw();target.querySelector('select').onchange=draw;
 async function manage(id){const dialog=document.querySelector('#detail'),body=document.querySelector('#detail-content');body.innerHTML='<p>Loading assignment</p>';if(!dialog.open)dialog.showModal();
 try{const [t]=await read('v_task_detail',{task_id:id});if(!t)throw Error('Task is unavailable.');const candidateResult=await call('dispatch_candidates',{task_id:id}),candidates=candidateResult.data||[];
 body.innerHTML=`<p class="eyebrow">${escape(t.zone_name)}</p><h2>${escape(t.outcome)}</h2><p>Assigned to ${escape(t.assignee_name||'nobody')} · ${escape(t.state)}</p><label for="dispatch-reason">Reason or handoff note</label><input id="dispatch-reason"><div id="dispatch-error" role="alert"></div><div id="dispatch-actions"></div>`;
 const controls=body.querySelector('#dispatch-actions'),error=body.querySelector('#dispatch-error');
 async function run(fn,args){controls.querySelectorAll('button').forEach(b=>b.disabled=true);try{await act(fn,args,{taskId:id});dialog.close();}catch(e){fieldError(error,e);controls.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 if(['unassigned','assigned','accepted','in_progress'].includes(t.state)){
 controls.innerHTML=`<h3>Choose a person</h3>${candidates.map(p=>`<div class="candidate"><strong>${escape(p.full_name)}</strong><p class="muted">${escape(p.crew_name||'')} · ${escape(p.availability||'')}<br>${p.missing_capabilities?.length?'Missing: '+escape(p.missing_capabilities.join(', ')):'Required certifications held'}${p.current_task?'<br>Current work: '+escape(typeof p.current_task==='string'?p.current_task:p.current_task.outcome||'Assigned work'):''}</p><button data-person="${p.profile_id}" ${p.missing_capabilities?.length||p.profile_id===t.assignee_id?'disabled':''}>${t.assignee_id?'Reassign remaining work':'Assign'}</button></div>`).join('')}`;
 controls.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>run(t.assignee_id?'assignment_reassign':'task_assign',t.assignee_id?{task_id:id,to_profile_id:b.dataset.person,expected_revision:t.task_revision,keep_asset:true,reason:body.querySelector('input').value}:{task_id:id,profile_id:b.dataset.person,expected_revision:t.task_revision,...(t.asset_id?{asset_id:t.asset_id}:{}),note:body.querySelector('input').value}));
 }
 if(['assigned','accepted'].includes(t.state)&&t.assignment_id){controls.insertAdjacentHTML('beforeend','<button id="release">Release assignment</button>');controls.querySelector('#release').onclick=()=>{const reason=body.querySelector('input').value.trim();if(!reason)return fieldError(error,Error('Enter a release reason.'));run('assignment_release',{assignment_id:t.assignment_id,expected_revision:t.task_revision,reason});};}
 if(t.state==='review'&&['lead','admin'].includes(me.app_role)){controls.insertAdjacentHTML('beforeend','<p>Review the service record before approving.</p><pre id="record-summary"></pre><button id="approve">Approve completion</button>');controls.querySelector('#record-summary').textContent=JSON.stringify(t.service_record,(k,v)=>/hash|seq/i.test(k)?undefined:v,2);controls.querySelector('#approve').onclick=()=>run('task_approve',{task_id:id,expected_revision:t.task_revision,note:body.querySelector('input').value});}
 }catch(e){body.textContent=e.message;}
 }
 return tasks;
}
export async function showPeople(target,{read}){const people=await read('v_crew_availability',{},'full_name');target.innerHTML=`<h1>People and crews</h1><h2>Available to help</h2><div class="live-list">${people.filter(p=>p.availability==='free').map(p=>`<article class="card"><h3>${escape(p.full_name)}</h3><p>${escape(p.crew_name||'No crew')} · On shift</p></article>`).join('')||'<p>No available people in your view.</p>'}</div><h2>Crews at a glance</h2>${people.map(p=>`<p>${escape(p.full_name)} · ${escape(p.crew_name||'No crew')} · ${escape(p.availability)} · ${p.open_task_count} open tasks</p>`).join('')}`;}
