import {load,save} from './store.mjs';
import {escape,fieldError} from './worker.mjs';
export async function showProof(task,{owner}){
 const body=document.querySelector('#detail-content'),key='proof:'+task.task_id;
 const draft=await load(owner,key,{photos:[],notes:'',quantity:'',material:'bulk_salt',action:'other'});
 body.innerHTML=`<p class="eyebrow">${escape(task.zone_name)}</p><h2>Complete service record</h2><p>${escape(task.outcome)}</p><div class="callout">Photo upload is unavailable until the server supports registration without a client hash. Originals are saved only on this device. No completion is sent.</div><form id="proof-form"><label for="proof-action">Work completed</label><select id="proof-action">${['plowed','shoveled','salted','sanded','brined','mowed','trimmed','inspected','other'].map(a=>`<option>${a}</option>`).join('')}</select>${['before','after'].map(kind=>`<label for="photo-${kind}">${kind} photo</label><input id="photo-${kind}" type="file" accept="image/jpeg,image/png,image/heic" capture="environment"><p data-field="photos.${kind}" role="alert"></p>`).join('')}<div id="saved-photos"></div><label for="proof-material">Material</label><select id="proof-material"><option value="bulk_salt">Bulk salt · lb</option><option value="sand">Sand · lb</option><option value="brine">Brine · gal</option></select><label for="proof-quantity">Quantity applied</label><input id="proof-quantity" type="number" min="0" step="any" value="${escape(draft.quantity)}"><p data-field="materials" role="alert"></p><label for="proof-notes">Completion notes</label><textarea id="proof-notes">${escape(draft.notes)}</textarea><button type="submit">Save draft</button><button type="button" disabled>Submission unavailable</button><div id="proof-error" role="alert"></div></form>`;
 const q=s=>body.querySelector(s);q('#proof-action').value=draft.action;q('#proof-material').value=draft.material;
 function photos(){q('#saved-photos').innerHTML=draft.photos.map(p=>`<p>${escape(p.kind)} · ${escape(p.name)} · Original saved</p>`).join('');}photos();
 for(const kind of ['before','after'])q('#photo-'+kind).onchange=async event=>{try{const file=event.target.files[0];if(!file)return;const type=file.type||(/\.heic$/i.test(file.name)?'image/heic':'');if(!['image/jpeg','image/png','image/heic'].includes(type)||file.size>8*1024*1024)throw Error('Choose an original JPEG, PNG, or HEIC photo up to 8 MB.');draft.photos.push({client_photo_id:crypto.randomUUID(),kind,blob:file,name:file.name,selected_at:new Date().toISOString()});await save(owner,key,draft);photos();}catch(e){q(`[data-field="photos.${kind}"]`).textContent=e.message;}};
 q('form').onsubmit=async event=>{event.preventDefault();try{draft.action=q('#proof-action').value;draft.material=q('#proof-material').value;draft.quantity=q('#proof-quantity').value;draft.notes=q('#proof-notes').value;if(draft.quantity!==''&&(!Number.isFinite(Number(draft.quantity))||Number(draft.quantity)<0))throw Object.assign(Error('Enter a quantity of zero or greater.'),{details:{fields:['materials']}});await save(owner,key,draft);q('#proof-error').textContent='Draft saved on this device. Nothing uploaded or submitted.';}catch(e){fieldError(q('#proof-error'),e);}};
}
