export const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const displayTime=v=>v?new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'Not scheduled';
export function fieldError(target,error){
 target.textContent=error.message;const fields=error.details?.fields||error.details?.missing||[];
 for(const field of fields){const line=document.createElement('div');line.className='field-error';line.textContent=field.replaceAll('_',' ');target.append(line);}
}
export function getLocation(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(Error('Location is unavailable on this device.'));navigator.geolocation.getCurrentPosition(p=>resolve({lng:p.coords.longitude,lat:p.coords.latitude,accuracy_m:p.coords.accuracy,taken_at:new Date(p.timestamp).toISOString()}),()=>reject(Error('Location is unavailable. Allow location access and try again.')),{enableHighAccuracy:true,maximumAge:15000,timeout:15000});});}
export function taskCards(tasks){return `<div class="live-list">${tasks.map((t,i)=>`<article class="card">${i===1?'<p class="eyebrow">After this</p>':''}<div class="card-head"><span class="tag">Priority ${t.priority} · ${escape(t.zone_name)}</span><span class="state">${escape(t.state.replaceAll('_',' '))}${t.pending?' · pending':''}</span></div><h2>${escape(t.outcome)}</h2><p class="muted">${escape(t.asset_name||'No equipment assigned')}<br>${escape(displayTime(t.scheduled_start))}</p>${t.keepout_active?`<p>Keep-out: ${escape(t.keepout_reason)}</p>`:''}<button data-task="${escape(t.task_id)}">View task</button></article>`).join('')||'<article class="card">No active assignments.</article>'}</div>`;}
export async function taskDetail(id,{read,act,me,onLocation,proof}){
 const dialog=document.querySelector('#detail'),body=document.querySelector('#detail-content');body.innerHTML='<p>Loading task</p>';if(!dialog.open)dialog.showModal();
 try{const [t]=await read('v_task_detail',{task_id:id});if(!t)throw Error('This task is no longer available.');
 body.innerHTML=`<p class="eyebrow">${escape(t.zone_name)} · ${escape(t.state)}</p><h2>${escape(t.outcome)}</h2><p>${escape(t.description||'')}</p><p class="muted">${escape(t.asset_name||'No equipment assigned')}</p><p>${escape(t.blocked_reason||'')}</p><div id="worker-actions"></div><div id="worker-error" role="alert"></div>`;
 const actions=body.querySelector('#worker-actions'),error=body.querySelector('#worker-error');if(t.assignee_id!==me.id||me.app_role==='oversight'){actions.textContent='Worker actions are available to the current assignee.';return;}
 async function run(fn,args){actions.querySelectorAll('button').forEach(b=>b.disabled=true);try{await act(fn,args,{taskId:id});dialog.close();}catch(e){fieldError(error,e);actions.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 if(t.state==='assigned'){actions.innerHTML='<button id="acknowledge" class="primary">Accept assignment</button>';actions.querySelector('button').onclick=()=>run('assignment_acknowledge',{assignment_id:t.assignment_id,expected_revision:t.task_revision});}
 if(t.state==='accepted'){actions.innerHTML='<button id="begin-task" class="primary">Start task with location</button>';actions.querySelector('button').onclick=async()=>{try{const location=await getLocation();await onLocation(location);await run('task_start',{task_id:id,expected_revision:t.task_revision,location});}catch(e){fieldError(error,e);}};}
 if(t.state==='in_progress'){const button=document.createElement('button');button.textContent='Complete service record';button.onclick=()=>proof(t);actions.append(button);}
 if(['assigned','accepted','in_progress'].includes(t.state)){actions.insertAdjacentHTML('beforeend','<label for="block-reason">What is blocking the work?</label><input id="block-reason"><button id="block-task">Report blocked task</button>');actions.querySelector('#block-task').onclick=()=>{const reason=actions.querySelector('input').value.trim();if(!reason)return fieldError(error,Error('Describe the blocker.'));run('task_block',{task_id:id,expected_revision:t.task_revision,reason});};}
 }catch(e){body.textContent=e.message;}
}
