"""
Bundle data/*.geojson and data/config.json into data/bundle.js so index.html
works when opened straight from a file on a computer (no web server).
On GitHub Pages the page fetches the .geojson files directly and the bundle
is only a fallback, but keep it current: run this after editing any data file.

Run:  python3 tools/build.py
"""
import json, os, glob

DATA = os.path.join(os.path.dirname(__file__), "..", "data")
out = {"layers": {}, "config": {}}

with open(os.path.join(DATA, "config.json")) as f:
    out["config"] = json.load(f)

for path in sorted(glob.glob(os.path.join(DATA, "*.geojson"))):
    key = os.path.splitext(os.path.basename(path))[0]
    with open(path) as f:
        fc = json.load(f)
    # light validation so a bad edit fails here instead of silently in the browser
    assert fc.get("type") == "FeatureCollection", f"{key}: not a FeatureCollection"
    ids = set()
    for ft in fc["features"]:
        p = ft.get("properties", {})
        assert "id" in p and "name" in p, f"{key}: feature missing id or name: {p}"
        assert p["id"] not in ids, f"{key}: duplicate id {p['id']}"
        ids.add(p["id"])
    out["layers"][key] = fc
    print(f"{key}: {len(fc['features'])} features")

with open(os.path.join(DATA, "bundle.js"), "w") as f:
    f.write("// GENERATED by tools/build.py. Do not edit. Edit the .geojson files and rebuild.\n")
    f.write("window.UND_MAP_BUNDLE = ")
    json.dump(out, f, separators=(",", ":"))
    f.write(";\n")
print("wrote data/bundle.js")
